project:
  type: website
  render:
    - index.qmd

website:
  description: "Atharva Ingle — Personal Website"
  site-url: https://your-website-url.example.com # update when domain is ready
  title: "Atharva Ingle"
  navbar:
    right:
      - icon: github
        href: https://github.com/Gladiator07
      - icon: twitter
        href: https://twitter.com/AtharvaIngle7
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css

