project:
  type: website
  resources:
    - CNAME
website:
  description: "Atharva Ingle — Personal Website"
  site-url: https://atharvaingle.dev
  favicon: assets/favicon.ico
  page-navigation: true
  title: "Atharva"
  navbar:
    left:
      - text: About
        href: about.qmd
      - text: Blog
        href: blogs.qmd
    right:
      - text: "<img src='/assets/kaggle_icon.svg' alt='Kaggle' class='nav-icon' />"
        href: https://www.kaggle.com/atharvaingle
        aria-label: Kaggle
        target: _blank
      - icon: github
        href: https://github.com/Gladiator07
        target: _blank
      - icon: twitter
        href: https://twitter.com/AtharvaIngle7
        target: _blank
      - icon: linkedin
        href: https://www.linkedin.com/in/atharva-ingle-564430187/
        target: _blank
      - icon: rss
        href: /blogs.xml
        target: _blank
      - icon: substack
        href: https://atharvaingle.substack.com/
        target: _blank


  image: "assets/profile.jpg"
  image-alt: "Atharva Ingle website social preview"
  open-graph: true
  twitter-card:
    site: "@AtharvaIngle7"
    card-style: summary_large_image
    title: "Atharva Ingle"
    description: "Personal Website of Atharva Ingle"
    image: "assets/profile.jpg"

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    link-external-icon: true
    link-external-newwindow: true
    respect-user-color-scheme: false
    mainfont: "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', 'Inter', 'Noto Sans', Arial, sans-serif"
    monofont: "'SF Mono', 'Monaco', 'Inconsolata', 'Fira Code', 'JetBrains Mono', 'Source Code Pro', 'Consolas', 'Courier New', monospace"
    fontsize: 1.05em
    linestretch: 1.6
    include-in-header: header.html

execute:
  freeze: auto
